-- Enhanced CRM Features Migration

-- Email Templates
CREATE TABLE "crm_email_templates" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "subject" TEXT NOT NULL,
    "body" TEXT NOT NULL,
    "category" TEXT NOT NULL DEFAULT 'GENERAL',
    "variables" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdById" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "crm_email_templates_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "platform_users" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Emails sent from CRM
CREATE TABLE "crm_emails" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "leadId" TEXT,
    "toEmail" TEXT NOT NULL,
    "toName" TEXT,
    "ccEmails" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "bccEmails" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "subject" TEXT NOT NULL,
    "body" TEXT NOT NULL,
    "isHtml" BOOLEAN NOT NULL DEFAULT true,
    "templateId" TEXT,
    "attachments" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "status" TEXT NOT NULL DEFAULT 'PENDING',
    "sentAt" TIMESTAMP(3),
    "openedAt" TIMESTAMP(3),
    "clickedAt" TIMESTAMP(3),
    "openCount" INTEGER NOT NULL DEFAULT 0,
    "clickCount" INTEGER NOT NULL DEFAULT 0,
    "errorMessage" TEXT,
    "retryCount" INTEGER NOT NULL DEFAULT 0,
    "sentById" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "crm_emails_leadId_fkey" FOREIGN KEY ("leadId") REFERENCES "crm_leads" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "crm_emails_templateId_fkey" FOREIGN KEY ("templateId") REFERENCES "crm_email_templates" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "crm_emails_sentById_fkey" FOREIGN KEY ("sentById") REFERENCES "platform_users" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE INDEX "crm_emails_leadId_idx" ON "crm_emails"("leadId");
CREATE INDEX "crm_emails_status_idx" ON "crm_emails"("status");
CREATE INDEX "crm_emails_sentById_idx" ON "crm_emails"("sentById");

-- Documents
CREATE TABLE "crm_documents" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "fileUrl" TEXT NOT NULL,
    "fileSize" INTEGER NOT NULL,
    "fileType" TEXT NOT NULL,
    "mimeType" TEXT NOT NULL,
    "category" TEXT NOT NULL DEFAULT 'OTHER',
    "leadId" TEXT,
    "dealId" TEXT,
    "version" INTEGER NOT NULL DEFAULT 1,
    "parentDocumentId" TEXT,
    "uploadedById" TEXT NOT NULL,
    "viewCount" INTEGER NOT NULL DEFAULT 0,
    "lastViewedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "crm_documents_leadId_fkey" FOREIGN KEY ("leadId") REFERENCES "crm_leads" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "crm_documents_dealId_fkey" FOREIGN KEY ("dealId") REFERENCES "crm_deals" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "crm_documents_uploadedById_fkey" FOREIGN KEY ("uploadedById") REFERENCES "platform_users" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE INDEX "crm_documents_leadId_idx" ON "crm_documents"("leadId");
CREATE INDEX "crm_documents_dealId_idx" ON "crm_documents"("dealId");
CREATE INDEX "crm_documents_category_idx" ON "crm_documents"("category");

-- Follow-up Reminders
CREATE TABLE "crm_follow_up_reminders" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "leadId" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT,
    "reminderDate" TIMESTAMP(3) NOT NULL,
    "reminderType" TEXT NOT NULL DEFAULT 'FOLLOW_UP',
    "priority" TEXT NOT NULL DEFAULT 'MEDIUM',
    "status" TEXT NOT NULL DEFAULT 'PENDING',
    "completedAt" TIMESTAMP(3),
    "dismissedAt" TIMESTAMP(3),
    "snoozeUntil" TIMESTAMP(3),
    "assignedToId" TEXT NOT NULL,
    "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false,
    "autoRule" TEXT,
    "notificationSent" BOOLEAN NOT NULL DEFAULT false,
    "notificationSentAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "crm_follow_up_reminders_leadId_fkey" FOREIGN KEY ("leadId") REFERENCES "crm_leads" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "crm_follow_up_reminders_assignedToId_fkey" FOREIGN KEY ("assignedToId") REFERENCES "platform_users" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE INDEX "crm_follow_up_reminders_leadId_idx" ON "crm_follow_up_reminders"("leadId");
CREATE INDEX "crm_follow_up_reminders_assignedToId_status_idx" ON "crm_follow_up_reminders"("assignedToId", "status");
CREATE INDEX "crm_follow_up_reminders_reminderDate_status_idx" ON "crm_follow_up_reminders"("reminderDate", "status");

-- Lead Scoring
CREATE TABLE "crm_lead_scores" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "leadId" TEXT NOT NULL UNIQUE,
    "totalScore" INTEGER NOT NULL DEFAULT 0,
    "engagementScore" INTEGER NOT NULL DEFAULT 0,
    "fitScore" INTEGER NOT NULL DEFAULT 0,
    "intentScore" INTEGER NOT NULL DEFAULT 0,
    "emailOpens" INTEGER NOT NULL DEFAULT 0,
    "emailClicks" INTEGER NOT NULL DEFAULT 0,
    "websiteVisits" INTEGER NOT NULL DEFAULT 0,
    "demoRequested" BOOLEAN NOT NULL DEFAULT false,
    "budgetConfirmed" BOOLEAN NOT NULL DEFAULT false,
    "decisionMaker" BOOLEAN NOT NULL DEFAULT false,
    "grade" TEXT NOT NULL DEFAULT 'C',
    "lastCalculatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "crm_lead_scores_leadId_fkey" FOREIGN KEY ("leadId") REFERENCES "crm_leads" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Quotes
CREATE TABLE "crm_quotes" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "quoteNumber" TEXT NOT NULL UNIQUE,
    "leadId" TEXT NOT NULL,
    "dealId" TEXT,
    "title" TEXT NOT NULL,
    "description" TEXT,
    "subtotal" DECIMAL(12,2) NOT NULL,
    "taxAmount" DECIMAL(12,2) NOT NULL DEFAULT 0,
    "discountAmount" DECIMAL(12,2) NOT NULL DEFAULT 0,
    "totalAmount" DECIMAL(12,2) NOT NULL,
    "currency" TEXT NOT NULL DEFAULT 'ZMW',
    "validUntil" TIMESTAMP(3) NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'DRAFT',
    "sentAt" TIMESTAMP(3),
    "viewedAt" TIMESTAMP(3),
    "acceptedAt" TIMESTAMP(3),
    "rejectedAt" TIMESTAMP(3),
    "paymentTerms" TEXT,
    "deliveryTerms" TEXT,
    "notes" TEXT,
    "pdfUrl" TEXT,
    "createdById" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "crm_quotes_leadId_fkey" FOREIGN KEY ("leadId") REFERENCES "crm_leads" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "crm_quotes_dealId_fkey" FOREIGN KEY ("dealId") REFERENCES "crm_deals" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "crm_quotes_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "platform_users" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE INDEX "crm_quotes_leadId_idx" ON "crm_quotes"("leadId");
CREATE INDEX "crm_quotes_dealId_idx" ON "crm_quotes"("dealId");
CREATE INDEX "crm_quotes_status_idx" ON "crm_quotes"("status");

-- Quote Items
CREATE TABLE "crm_quote_items" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "quoteId" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "quantity" INTEGER NOT NULL DEFAULT 1,
    "unitPrice" DECIMAL(10,2) NOT NULL,
    "amount" DECIMAL(12,2) NOT NULL,
    "planTier" TEXT,
    "billingCycle" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "crm_quote_items_quoteId_fkey" FOREIGN KEY ("quoteId") REFERENCES "crm_quotes" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CRM Reports
CREATE TABLE "crm_reports" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "reportType" TEXT NOT NULL,
    "periodStart" TIMESTAMP(3) NOT NULL,
    "periodEnd" TIMESTAMP(3) NOT NULL,
    "data" JSONB NOT NULL,
    "totalLeads" INTEGER NOT NULL DEFAULT 0,
    "convertedLeads" INTEGER NOT NULL DEFAULT 0,
    "conversionRate" DECIMAL(5,2) NOT NULL DEFAULT 0,
    "totalRevenue" DECIMAL(12,2) NOT NULL DEFAULT 0,
    "avgDealSize" DECIMAL(12,2) NOT NULL DEFAULT 0,
    "avgSalesCycle" INTEGER NOT NULL DEFAULT 0,
    "generatedById" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "crm_reports_generatedById_fkey" FOREIGN KEY ("generatedById") REFERENCES "platform_users" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE INDEX "crm_reports_reportType_idx" ON "crm_reports"("reportType");
CREATE INDEX "crm_reports_periodStart_periodEnd_idx" ON "crm_reports"("periodStart", "periodEnd");
